"""add favourite flag to chat sessions

Revision ID: 4367b5c0c1af
Revises: 688bf792103b
Create Date: 2026-04-26 01:18:27.365849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4367b5c0c1af'
down_revision: Union[str, Sequence[str], None] = '688bf792103b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
 
    # Add favourite flag to saved chat sessions.
    # server_default="0" makes all existing chats start as NOT favourite.
    op.add_column(
        "chat_sessions",
        sa.Column(
            "is_favorite",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("0"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'is_favorite')
    # ### end Alembic commands ###
